// Generated by CoffeeScript 1.3.3
var MeCab;

MeCab = (function() {

  function MeCab() {
    var _this = this;
    this.process = require('child_process').spawn("mecab", [], {
      detached: true
    });
    this.process.stdout.setEncoding("utf8");
    this.process.stdout.on("data", function(data) {
      var block, blocks, params, _i, _len, _results;
      blocks = data.split("\nEOS\n");
      _results = [];
      for (_i = 0, _len = blocks.length; _i < _len; _i++) {
        block = blocks[_i];
        params = block.split("\n").map(function(line) {
          return line.replace(/^.+\t/, "").split(",");
        });
        if (_this.queue[0]) {
          _this.queue[0](params);
          _results.push(_this.queue.splice(0, 1));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    this.queue = [];
  }

  MeCab.prototype.parse = function(str, callback) {
    this.queue.push(callback);
    return this.process.stdin.write(str + "\n");
  };

  MeCab.prototype.wakachi = function(str, callback) {
    return this.parse(str, function(result) {
      return callback(result.map(function(arr) {
        return arr[6];
      }));
    });
  };

  MeCab.prototype.close = function() {
    var _this = this;
    if (this.queue.length === 0) {
      return this.process.kill();
    } else {
      return setTimeout(function() {
        return _this.close();
      });
    }
  };

  return MeCab;

})();

module.exports = MeCab;