// Generated by CoffeeScript 1.3.3
var MeCab, mecab;

MeCab = require("./mecab-simple.js");

mecab = new MeCab();

mecab.parse('すもももももももものうち', function(result) {
  return console.log(result);
});

mecab.wakachi('すもももももももものうち', function(result) {
  return console.log(result);
});

mecab.close();
